// import logo from './logo.svg';
import './App.css';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';
// import PersonalInfo from './components/PersonalInfo/PersonalInfo';
// import AddressInfo from './components/AddressInfo/AddressInfo';
// import Confirmation from './components/Confirmation/Confirmation';
import StepDisplay from './components/StepDisplay/StepDisplay';
import { useState } from 'react';
import FormContent from './components/FormContent/FormContent';





function App() {
  const [currStep,setCurrStep]=useState(1);
  const forward = () => {
    if (currStep < 3) {
      setCurrStep(currStep + 1);
    }
  }

  const backward = () => {
    if (currStep > 1) {
      setCurrStep(currStep - 1);
    }
  }
  
  
 /* Delivered code generated by Create New App
 return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );*/

  //Code for the Multistep Form

  return(
  
  <div>
    <Header/>
    
    <StepDisplay currStep={currStep}/>
    <FormContent currStep={currStep}/>
    <Navbar currStep={currStep} forward={forward} backward={backward}/>
    <Footer/>
  </div>
  );

}

export default App;
