// import logo from './logo.svg';
import './App.css';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';
import StepDisplay from './components/StepDisplay/StepDisplay';
import { useState,useEffect } from 'react';
import FormContent from './components/FormContent/FormContent';



function App() {
  
  // State to track the current step in the form
  const [currStep,setCurrStep]=useState(1);

   // State to hold form data
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    address1: '',
    address2: '',
    city: '',
    state: '',
    zip: '',

  });

   // State to hold form validation errors
  const [errors, setErrors] = useState({});

    // State to track if it's the initial load of the form (for localStorage)
  const [isInitialLoad, setIsInitialLoad] = useState(true);


  // Load form data from localStorage on component mount
  useEffect(() => {
   
    const savedData = JSON.parse(localStorage.getItem('formData'));
    if (savedData) {
      setIsInitialLoad(false);
      setFormData(savedData);
    }
  }, []);

 // Save form data to localStorage when it changes (excluding the initial load)
  useEffect(() => {
    if(!isInitialLoad){
    localStorage.setItem('formData', JSON.stringify(formData));
    } 
  }, [formData,isInitialLoad]);

   // Handle form field changes and update the formData state
  const handleForm=({name, value})=>{
    setFormData((prev) => ({ ...prev, [name]: value }));
  }

  // Validate the form based on the current step
  const validateStep = (step) => {
    let tempErrors = {};
    if (step === 1) {
      // Validate the fields in step 1 (Personal Information)
      if (!formData.name) tempErrors.name = 'Name is required';
      if (!/^[a-zA-Z]+$/.test(formData.name))  tempErrors.name = "Name can only contain alphabets";
      if (!formData.email) tempErrors.email = 'Email is required';
      if (!/\S+@\S+\.\S+/.test(formData.email)) tempErrors.email = "Email is invalid";
      if (!formData.phone) tempErrors.phone = 'Phone is required';
      if (!(formData.phone.length===10)) tempErrors.phone = 'Phone number should be less than 10 digits';
      if (!/^\d+$/.test(formData.phone)) tempErrors.phone = "Phone number is invalid";
    } else if (step === 2) {
      // Validate the fields in step 2 (Address Information)
      if (!formData.address1) tempErrors.address1 = 'Address Line 1 is required';
      if (!formData.city) tempErrors.city = 'City is required';
      if (!formData.state) tempErrors.state = 'State is required';
      if (!formData.zip) tempErrors.zip = 'Zip Code is required';
      if (!(formData.zip.length===6)) tempErrors.zip = 'Zip code should have 6 digits';
      if (!/^\d+$/.test(formData.zip)) tempErrors.zip = "Zip code is invalid";

    }
    setErrors(tempErrors);
    return Object.keys(tempErrors).length === 0;
  };


 // Function to move to the next step in the form
  const forward = () => {
    if (validateStep(currStep)) {
    if (currStep < 3) {
      setCurrStep(currStep + 1);
    }
  }
  else{
    alert("Please correct the mentioned errors");
  }
  }

   // Function to move to the previous step in the form
  const backward = () => {
    if (currStep > 1) {
      setCurrStep(currStep - 1);
    }
  }
  
  
 /* Delivered code generated by Create New App
 return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );*/

  //Code for the Multistep Form

  return(
  
  <div>
    <Header/>
    
    <StepDisplay currStep={currStep}/>
    <FormContent currStep={currStep}  formData={formData} handleForm={handleForm} errors={errors}  />
    <Navbar currStep={currStep} forward={forward} backward={backward}/>
    <Footer/>
  </div>
  );

}

export default App;
